version: "3"
services:
  sonarqube:
    image: sonarqube:8.9.7-community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
#  mysqldb:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_DATABASE: tpAchatProject
#      MYSQL_USER: user
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - '3306:3306'
#    volumes:
#      - my-db:/var/lib/mysql

volumes:
  nexus-data:
  sonarqube_logs:
  sonarqube_data:
  sonarqube_extensions:
  my-db: