version: '3'
services:
  ichrakcontainer:
    container_name: ichrakcontainer
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0000
    volumes:
      - /home/mysql/data:/var/lib/mysql
  spring_app:
    image: ichrakcontainer/my_devops
    container_name: tpachat
    restart: on-failure
    ports:
      - 9092:9092
    depends_on:
      - ichrakcontainer