version: '3'
services:
  db:
    container_name: db
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tpachato
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql
  backend:
    image: seif03/tpachatproject
    container_name: tpachatproject
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachato?useSSL=false
      - spring.datasource.username=user
      - spring.datasource.password=root
    depends_on:
      - db